api = "0.9"

[buildpack]
id = "planqk-buildpacks/job-template"
version = "0.0.1"
name = "PlanQK Job Template Buildpack"
homepage = "https://github.com/PlanQK/planqk-buildpacks"

[[targets]]
os = "linux"

[[stacks]]
id = "*"
