description = "PlanQK Builder (Ubuntu 22.04)"


[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/python:2.14.0"
version = "2.14.0"


[[order]]
    [[order.group]]
    id = "paketo-buildpacks/python"


[stack]
id = "io.buildpacks.stacks.jammy"
build-image = "docker.io/paketobuildpacks/build-jammy-full"
run-image = "index.docker.io/paketobuildpacks/run-jammy-base"
run-image-mirrors = []
