description = "Ubuntu 22.04 base image with buildpacks for Python, Procfile and the PlanQK Platform"


[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/python:2.9.0"
version = "2.9.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.6.4"
  version = "5.6.4"


[[order]]
    
    [[order.group]]
    id = "paketo-buildpacks/python"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.6.4"

[stack]
id = "io.buildpacks.stacks.jammy"
build-image = "docker.io/paketobuildpacks/build-jammy-full"
run-image = "index.docker.io/paketobuildpacks/run-jammy-full"
run-image-mirrors = []
