    [[build.env]]
      name = "BP_PIPFILE"
      value = "app/user_code/requirements.txt"

    [[build.env]]
      name = "BP_PYTHON_RUNTIME"
      value = "python"

    [[build.env]]
      name = "CONDA_ENV_FILE"
      value = "app/user_code/environment.yml"

    [[build.env]]
      name = "BP_ENV_DIR"
      value = "/workspace"

